config/routes.rb
CulturalRoutes::Application.routes.draw do |map|
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  
  Jammit::Routes.draw(map)

  scope "/monuments" do
    resources :artists
    resources :statues
    resources :entities
    resources :categories
  end

  scope "/literary-routes" do
    resources :authors
    resources :literary_routes, :path => "routes"
    resources :themes
    resources :books
  end

  resource :contacts, :only => [:new, :create]
  match "/page/contacts" => "contacts#new"

  match "admin" => "admin#index"
  
  match "page/:link"  => "main#link"

  match "api/statues/category/:id(.:format)" => "api#statues_by_category"
  match "api/statues/artist/:id(.:format)" => "api#statues_by_artist"
  match "api/statues/entity/:id(.:format)" => "api#statues_by_entity" 
  match "api/statues/author/:id(.:format)" => "api#statues_by_author" 
  match "api/statues/:id(.:format)" => "api#statue"
  match "api/assets/:id(.:format)" => "api#assets"
  match "api/routes" => "api#routes"
  match "api/routes/:id" => "api#route"
  match "api/location/:id" => "api#location"
  match "api/location/:id/detail" => "api#location_detail"
  namespace :admin do
    resources :pages, :only => [:show] do
      resources :blocks, :only => [:index, :edit, :update]
    end

    resources :artists do
      resources :related_works, :path => "related-work" do
        delete :delete, :on => :collection
      end
      
      delete :delete, :on => :collection
    end
    
    resources :categories do
      delete :delete, :on => :collection
    end
    
    resources :entities do
      delete :delete, :on => :collection
    end    
    
    resources :statues do
      delete :delete, :on => :collection

      resources :assets do
        delete :delete, :on => :collection
      end
    end
    
    resources :authors do
      delete :delete, :on => :collection
      get :routes, :on => :member
      get :books, :on => :member
    end
    
    resources :books do
      delete :delete, :on => :collection
    end
    
    resources :citations do
      delete :delete, :on => :collection
    end
    
    resources :themes do
      delete :delete, :on => :collection
    end
    
    resources :literary_routes, :path => "routes" do
      delete :delete, :on => :collection
      
      resources :locations do
        
        resources :assets do
          delete :delete, :on => :collection
        end
        
        delete :delete, :on => :collection
        put :bulk, :on => :collection
      end
    end
    
    resources :users
    
    
    match "assets/:id(.:format)" => "assets#asset"
    match "preview" => "admin#preview"
  end
  
  

  root :to => redirect("/page/home")

end

app/models/literary_route.rb
class LiteraryRoute < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  default_scope :order => 'name ASC'
  has_many :locations
  belongs_to :author
  has_and_belongs_to_many :themes
  
  validates_presence_of :name, :description
  
  accepts_nested_attributes_for :locations, :reject_if => proc { |attributes| attributes['location'].blank? }, :allow_destroy => true
  
  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.routes
    default_url_options[:host] = 'www.fragmentized.net'
    all_routes = []
    self.includes(:locations).all.each do |route|
      all_routes << {
        :name => route.name,
        :latitude => route.locations.first.latitude,
        :longitude => route.locations.first.longitude,
        :url => route.literary_route_path(route)
      } if route.locations.any?
    end
    all_routes
  end
end

app/views/shared/_admin_table_actions.html.haml
%ul.table-bar.clearfix
	%li
		= link_to image_tag("/images/add.png") + _('Adicionar'), path, :class => "button add-button"
	%li
		%button{:type => "submit", :class => "button"}
			= image_tag("/images/delete.png") + _("Apagar")
	%li.right
		= will_paginate table

app/views/shared/_artist_form.html.haml
= render "shared/model_validation", :current_model => @artist

= form_for [:admin, @artist], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :name
			%li.uncertain-date
				= form.label :birthdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_birthdate
					= form.label :uncertain_birthdate, nil, :class => "checkbox"
					)
				= form.text_field :birthdate
			%li.uncertain-date
				= form.label :deathdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_deathdate
					= form.label :uncertain_deathdate, nil, :class => "checkbox"
					)
				= form.text_field :deathdate
			%li
				= form.text_area :biography, :rows => 10
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						Guardar
					%span.bright Ou
					= link_to "Cancelar", [:admin, :artists], :class => "cancel-button"

app/views/shared/_assets_form_classic.html.haml
= form_for(assetable_url(:admin, @assetable, @asset), :html => { :multipart => true, :id => "html-upload" }, :builder => LabellingWithErrorsFormBuilder) do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :title, :class => "asset-title"
			%li
				= form.text_area :description, :rows => 10, :class => "asset-description"
			%li
				= form.file_field :asset, :id => "upload-field", :example => _("(Ficheiros do tipo: gif, jpg, png, avi, mov)")
				#asset_asset_content_type
				#asset_asset_file_size
				%input{ :type => "hidden", :value => "image", :name => "asset[media_type]" }
				%input{ :type => "hidden", :value => "1", :name => "asset[local_file]" }
			- unless @asset.new_record?
				%li.clearfix
					= render "shared/media_info"
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						= _("Guardar")
					%span.bright Ou
					= link_to "Cancelar", assetable_url(:admin, @assetable, :assets)

app/views/shared/_author_form.html.haml
= render "shared/model_validation", :current_model => @author
	
= form_for [:admin, @author], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :name
			%li.uncertain-date
				= form.label :birthdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_birthdate
					= form.label :uncertain_birthdate, nil, :class => "checkbox"
					)
				= form.text_field :birthdate
			%li.uncertain-date
				= form.label :deathdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_birthdate
					= form.label :uncertain_deathdate, nil, :class => "checkbox"
					)
				= form.text_field :deathdate
			%li
				= form.text_area :biography, :rows => 10
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						= _("Guardar")
					%span.bright Ou
					= link_to "Cancelar", [:admin, :authors], :class => "cancel-button"

app/views/shared/_block_form.html.haml
= render "shared/model_validation", :current_model => @block
  
= form_for [:admin, @page, @block], :builder => LabellingWithErrorsFormBuilder do |form|
  %fieldset
    %ul.form
      %li.first
        = form.text_field :title
      %li 
        = form.text_area :content
      %li.actions.clearfix
        %span.right
          %button.button{:type => "submit"}
            = image_tag("/images/add.png")
            Guardar
          %span.bright Ou
          = link_to "Cancelar", [:admin, @page], :class => "cancel-button"
      

app/views/shared/_book_form.html.haml
= render "shared/model_validation", :current_model => @book
	
= form_for [:admin, @book], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :title
			%li
				= form.collection_select(:author_ids, Author.all, :id, :name, { :include_blank => _("Selecione autor") }, { :name => "", "data-name" => "book[author_ids][]",  :id => "authors_books_ids", :class => "multi-select"})
				= link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :author], :class => "add-new", "data-title" => _("Adicionar Autor"), "data-source" => "authors_books_ids"
				= render :partial => "author", :collection => @book.authors.all
			%li
				= form.text_field :date
			%li
				= form.text_field :location
			%li
				= form.text_field :publisher
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						= _("Guardar")
					%span.bright Ou
					= link_to "Cancelar", [:admin, :books], :class => "cancel-button"

app/views/shared/_citation_form.html.haml
= render "shared/model_validation", :current_model => @citation
	
= form_for [:admin, @citation], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_area :citation, :rows => 10
			%li
				= form.collection_select(:book_id, Book.all, :id, :title, :include_blank => _("Selecione Livro"))
				= link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :book], :class => "add-new", "data-title" => _("Adicionar Livro"), "data-source" => "citation_book_id"
				
			%li
				= form.collection_select(:location_id, Location.all, :id, :name, :include_blank => _("Selecione Localização"))
			%li
				= form.text_field :pages
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						= _("Guardar")
					%span.bright Ou
					= link_to "Cancelar", [:admin, :citations]

app/views/shared/_entity_form.html.haml
= render "shared/model_validation", :current_model => @entity
	
= form_for [:admin, @entity], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :name
			%li.uncertain-date
				= form.label :birthdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_birthdate
					= form.label :uncertain_birthdate, nil, :class => "checkbox"
					)
				= form.text_field :birthdate
			%li.uncertain-date
				= form.label :deathdate, nil, :class => "checkbox"
				%span
					(
					= form.check_box :uncertain_deathdate
					= form.label :uncertain_deathdate, nil, :class => "checkbox"
					)
				= form.text_field :deathdate
			%li
				= form.text_area :description, :rows => 10
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						Guardar
					%span.bright Ou
					= link_to "Cancelar", [:admin, :entities], :class => "cancel-button"
			

app/views/shared/_header.html.haml
#header.clearfix
  %ul.nav.clearfix
    %li.contacts
      %a{ :href => '/page/contacts'}= _('Contactos')
    %li.about
      %a{ :href => '/page/about'}= _('Sobre')
    %li.home
      %a{ :href => '/page/home'}= _('Home')

app/views/shared/_literary_route_form.html.haml
- javascript do
  :javascript
    jQuery(function() {
      var mapOptions = {
        locationFor: "location",
        locationElement: "#location",
        geocodeButton: "#spot-location-search-button",
        addMarkerButton: "#spot-location-add-button",
        mapOverlay: "#map-overlay",
        mapCanvas: "#map-canvas",
        form: "form#route-form",
        newRecord: #{@literary_route.new_record? ? true : false},
        sortable: true,
        locationsGet: "#{@literary_route.new_record? ? "" : admin_literary_route_locations_path(@literary_route)}",
        locationsUpdate: "#{@literary_route.new_record? ? "" : admin_literary_route_locations_path(@literary_route)}",
        newLocations: "#new-location-fields",
        coordinatePrecision: 6,
        handleUpdate: true,
        inputTemplate: {
          latitude: '<input name="literary_route[locations_attributes][INDEX][latitude]" type="hidden" />',
          longitude: '<input name="literary_route[locations_attributes][INDEX][longitude]" type="hidden" />',
          location: '<input name="literary_route[locations_attributes][INDEX][location]" type="hidden" />',
          weight: '<input name="literary_route[locations_attributes][INDEX][weight]" type="hidden" />'
        }
      };
      new Fragmentized.AddRoute(mapOptions);
    });
  
= render "shared/model_validation", :current_model => @literary_route

= form_for [:admin, @literary_route], :builder => LabellingWithErrorsFormBuilder, :remote => true, :html => { :id => "route-form" } do |form|
  %fieldset
    %ul.form
      %li.first
        = form.hidden_field :id unless @literary_route.new_record?
        = form.text_field :name
      %li
        - if flash.include?(:author_id)
          = form.collection_select(:author_id, Author.all, :id, :name, :include_blank => _("Selecione autor"), :selected => flash[:author_id])
        - else
          = form.collection_select(:author_id, Author.all, :id, :name, :include_blank => _("Selecione autor"))
        = link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :author], :class => "add-new", "data-title" => _("Adicionar Autor"), "data-source" => "literary_route_author_id"
      %li
        = form.label :theme_ids
        = render :partial => "theme", :collection => @themes
      %li
        = form.text_area :description, :rows => 10
      %li
        .yui-gc
          .yui-u.first
            #new-location-fields.hidden
            = text_field_tag("location")
          .yui-u
            %a.button{:id => "spot-location-search-button", :href => "javascript:void(0)" }
              = image_tag("/images/world_go.png") 
              = _("Geocode")
            %a.button{:id => "spot-location-add-button", :href => "javascript:void(0)" }
              = image_tag("/images/add.png") 
              = _("Marcador")
        #location-info.top-spacer
          Latitude:
          %span#latitude-label
          |
          Longitude: 
          %span#longitude-label
        
        #map-canvas
      %li.actions.clearfix
        %span.right
          %button.button{:type => "submit"}
            = image_tag("/images/add.png")
            = _("Guardar")
          %span.bright Ou
          = link_to "Cancelar", [:admin, :literary_routes]

app/views/shared/_model_validation.html.haml
- if current_model.respond_to?(:errors) && current_model.errors.any?
	- content_for :validation do
		.validation
			= _("Oops! Foram detectados alguns erros no formulário. Por favor verifique os campos assinalados.")
			= image_tag("/images/cross.png", :class => "close-button");

app/views/shared/_statue_form.html.haml
- javascript do
  :javascript
    jQuery(function() {
      var mapOptions = {
        locationFor: "statue",
        locationElement: "#statue_location",
        geocodeButton: "#spot-location-search-button",
        addMarkerButton: "#spot-location-add-button",
        mapCanvas: "#map-canvas",
        form: "form#statue-form",
        mapOverlay: "#map-overlay",
        newRecord: #{@statue.new_record? ? true : false},
        locationsGet: "#{@statue.new_record? ? "" : admin_statue_path(@statue)}",
        locationsUpdate: "#{@statue.new_record? ? "" : admin_statues_path}",
        newLocations: "#new-location-fields",
        coordinatePrecision: 6,
        removeLast: true,
        handleUpdate: true,
        inputTemplate: {
          latitude: '<input name="statue[latitude]" type="hidden" />',
          longitude: '<input name="statue[longitude]" type="hidden" />',
        }
      };
      new Fragmentized.AddRoute(mapOptions);
    });  

= render "shared/model_validation", :current_model => @statue
  
= form_for [:admin, @statue], :builder => LabellingWithErrorsFormBuilder, :html => { :id => "statue-form" } do |form|
  %fieldset
    %ul.form
      %li.first
        = form.text_field :title
      %li
        = form.collection_select(:artist_id, Artist.all, :id, :name, :include_blank => _("Selecione artista"), :path => [:new, :admin, :artist])
        = link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :artist], :class => "add-new", "data-title" => _("Adicionar Artista"), "data-source" => "statue_artist_id"
      %li
        .yui-gf
          .yui-u.first
            = form.collection_select(:entity_id, Entity.all, :id, :name, :include_blank => _("Selecione entidade"), :path => [:new, :admin, :entity])
            = link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :entity], :class => "add-new", "data-title" => _("Adicionar Entidade"), "data-source" => "statue_entity_id"
          .yui-u
            = form.collection_select(:author_id, Author.all, :id, :name, :include_blank => _("Selecione autor"))
            = link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :author], :class => "add-new", "data-title" => _("Adicionar Autor"), "data-source" => "statue_author_id"
      %li
        = form.collection_select(:category_id, Category.all, :id, :name, :include_blank => _("Selecione categoria"), :path => [:new, :admin, :category])
        = link_to image_tag("/images/add.png", :class => "icon"), [:new, :admin, :category], :class => "add-new", "data-title" => _("Adicionar Categoria"), "data-source" => "statue_category_id"
      %li
        .yui-gc
          .yui-u.first
            #new-location-fields.hidden
            = form.text_field :location
          .yui-u
            .field-button
              %a{:class => "button", :id => "spot-location-search-button", :href => "javascript:void(0)"}
                = image_tag("/images/world_go.png") 
                = _("Geocode")
              %a{:class => "button", :id => "spot-location-add-button", :href => "javascript:void(0)"}
                = image_tag("/images/add.png") 
                = _("Posicionar")
        #location-info.top-spacer
          Latitude:
          %span#latitude-label
          |
          Longitude: 
          %span#longitude-label
        #map-canvas   

      %li
        = form.text_field :date
      %li
        = form.text_area :description, :rows => 10
      %li
        = form.text_area :comment, :rows => 10
      %li.actions.clearfix
        %span.right
          %button.button{:type => "submit"}
            = image_tag("/images/add.png")
            = _("Guardar")
          %span.bright Ou
          = link_to "Cancelar", [:admin, :statues]

app/views/shared/_support.html.haml
= render "shared/model_validation", :current_model => @contact

- unless @sent
  = form_for(@contact, :builder => LabellingWithErrorsFormBuilder, :url => "/admin" ) do |form|
    %fieldset
      %ul.form
        %li.first
          = form.text_field(:subject)
        %li
          = form.text_area(:message, :rows => 10, :cols => 70)
          = form.hidden_field(:email, :value => current_user.email)
        %li.actions.clearfix
          %span.right
            %button.button{ :type => :submit }
              = image_tag("email_go.png")
              = _("Enviar")
- else
  %p= _("Pedido de suporte registado!")

app/views/shared/_user_form.html.haml
= render "shared/model_validation", :current_model => @user
	
= form_for [:admin, @user], :builder => LabellingWithErrorsFormBuilder do |form|
	%fieldset
		%ul.form
			%li.first
				= form.text_field :email
			%li
				= form.password_field :password
			%li
				= form.password_field :password_confirmation
			%li.actions.clearfix
				%span.right
					%button.button{:type => "submit"}
						= image_tag("/images/add.png")
						= _("Guardar")
					%span.bright Ou
					= link_to "Cancelar", [:admin]